### ISSUE TITLE
NEW BUG: Connecting with my Android 14 device. The app is able to connect, but the wrong configs are shown and i can't change setting.

### ISSUE THREAD

**Issue by EDsteve** [EDsteve/ELOC-Control-Panel#18]
@josephx86 
I have tested the app (which is currently in Play store) on another Android 14 device which uses the stock ROM from Samsung. And it shows the same symptoms: For example sample rate and BT  is not showing or shows "Invalid" after a while. And settings can't be changed.
So it is not only on my PixelOS ROM. 

The modified version (which is the [current github version](https://github.com/EDsteve/ELOC-Control-Panel/commit/7e748022f25d33c918659a627f282f92a01a66f1)) works most of the time on Android 14. But sometimes the app crashes (At least on my PixelOS) with the option to wait, or close the app. When i click wait, the app continues working, but crashes again after a few seconds. This does not always happen. Haven't found out when or why it happens. Hope that info helps a bit.

BTW: I am flying to Thailand in 2 weeks and will send you the new ELOC hardware. That should make things easier for you as well.

**Comment by josephx86** [comment]
I have implemented pairing with a bluetooth device when app connects to the device for the first time. Pairing is required (Android 12 and up) to apply the name for the board that is set in config on the microSD card. 

On Android 12+, the app will also have a section in Bluetooth settings to unpair previously paired devices.

I have tested on my Samsung tablet and pairing is working fine. Please test on as usual and feel free to let me know if any devices are still having the bug.

**Comment by EDsteve** [comment]
Thanks so much.
I had to downgrade the Android APK from 8.7.2 to 8.5.1 in the build.gradle in order to make it compile on my Laptop. But after that all works.
Have tested it on my personal Android 14 device which works fine. Will do more tests on other devices when i am back home.

**Comment by EDsteve** [comment]
@josephx86 
I am using the app more often lately and i still get the crashes sometimes as you can see [here](https://photos.app.goo.gl/tuFPti3q6CWLzZSr8). Can't tell yet when or why this happens. Maybe you have an idea?

**Comment by EDsteve** [comment]
Haven't had any crashes lately. Some new commits might have fixed it. So i will close it.
